# Generated by Django 5.0.2 on 2024-02-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_loyal',
            field=models.BooleanField(default=False),
        ),
    ]
