# Generated by Django 5.0.2 on 2024-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_created_remove_product_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='room',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
